apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - 00-rbac/gitops-groups.yaml
  

components:
  - 01-components/application-controller-cluster-admin
  - 01-components/edge-termination
  - 01-components/enable-notifications
  - 01-components/gitops-admins
  - 01-components/kustomize-build-enable-helm

patches: 
  # - path: 00-rbac/gitops-admins-group.yaml

  - target:
      kind: ArgoCD
      name: openshift-gitops
    path: 03-replicas/patch-replicacount.yaml


      