apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Advanced Cluster Management for Kubernetes"
    # argocd.argoproj.io/sync-wave: "1"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: open-cluster-management
