apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-wave: "3"
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
