---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: hub-cluster-placement
  namespace: openshift-gitops
spec:
  clusterSets:
     - managed-clusters
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: env
          operator: "In"
          values:
          - hub
          - sandbox
          - test
          - prod

